/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eliminar;

import Inicio.ConexionSQL;
import Inicio.Login;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class Elminar_Registro_SalidaP extends javax.swing.JInternalFrame {

    ResultSet rs;
    String id="";
    int con=0;
    int seleccionar;
    public int datoLote=0;
    
    public Elminar_Registro_SalidaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEliminarRegiSalidaProd = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButtonRegresar2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ELIMINAR REGISTRO SALIDA PRODUCTO");

        tablaEliminarRegiSalidaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LOGIN", "FECHA", "OBSERVACIONES"
            }
        ));
        tablaEliminarRegiSalidaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEliminarRegiSalidaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEliminarRegiSalidaProd);

        jButton2.setText("MOSTRAR TODO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonRegresar2.setText("REGRESAR");
        jButtonRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresar2ActionPerformed(evt);
            }
        });

        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("FECHA REGISTRO 'YYYY-MM-DD'");

        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(47, 47, 47)
                                .addComponent(jButton2)
                                .addGap(54, 54, 54)
                                .addComponent(jButtonRegresar2)
                                .addGap(76, 76, 76)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButtonRegresar2)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEliminarRegiSalidaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEliminarRegiSalidaProdMouseClicked

        seleccionar=tablaEliminarRegiSalidaProd.rowAtPoint(evt.getPoint());
        this.id=String.valueOf(tablaEliminarRegiSalidaProd.getValueAt(seleccionar,0));
        con=Integer.parseInt(this.id);
        System.out.println("se selecciono"+con);
        consultaIdLote();
        
    }//GEN-LAST:event_tablaEliminarRegiSalidaProdMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel modelo=(DefaultTableModel) tablaEliminarRegiSalidaProd.getModel();
        String consulta="select re.IDUSUARIO, u.LOGINUSUARIO, re.FECHAREGISTROSALIDA, re.OBSERVACIONESSALIDA " +
        " from SALIDAREGISTRO as re join USUARIO as u on re.IDUSUARIO=u.IDUSUARIO ;" ;

        rs=ConexionSQL.Consulta(consulta);

        try {
                while (rs.next()){
                System.out.println(consulta);
                System.out.println(rs.getString("IDUSUARIO"));
                System.out.println(rs.getString("LOGINUSUARIO"));
                System.out.println(rs.getString("FECHAREGISTROSALIDA"));
                System.out.println(rs.getString("OBSERVACIONESSALIDA"));                
                modelo.addRow(new Object[] {rs.getString("IDUSUARIO"),rs.getString("LOGINUSUARIO"),rs.getString("FECHAREGISTROSALIDA"),
                rs.getString("OBSERVACIONESSALIDA")});
        }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresar2ActionPerformed
        limpiar();
        dispose();
    }//GEN-LAST:event_jButtonRegresar2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

          DefaultTableModel modelo=(DefaultTableModel) tablaEliminarRegiSalidaProd.getModel();
        String consulta="select re.IDUSUARIO,u.LOGINUSUARIO, re.FECHAREGISTROSALIDA, re.OBSERVACIONESSALIDA "
                    +"from SALIDAREGISTRO as re join USUARIO as u on re.IDUSUARIO=u.IDUSUARIO "
                + "where re.FECHAREGISTROSALIDA="+Buscar.getText()+";";
        rs=ConexionSQL.Consulta(consulta);

        try {
            while (rs.next()){
                 System.out.println(consulta);
                System.out.println(rs.getString("IDUSUARIO"));
                System.out.println(rs.getString("LOGINUSUARIO"));
                System.out.println(rs.getString("FECHAREGISTROSALIDA"));
                System.out.println(rs.getString("OBSERVACIONESSALIDA"));
                                
                modelo.addRow(new Object[] {rs.getString("IDUSUARIO"),rs.getString("LOGINUSUARIO"),rs.getString("FECHAREGISTROSALIDA"),
                rs.getString("OBSERVACIONESSALIDA")});

        }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // int idlote=consultaIdLote();
        String consulta1=" DELETE from lote where idlote="+this.datoLote+";";
       int d1=ConexionSQL.EliminarDato(consulta1); 
        System.out.println("se elmino: "+d1);
       String consulta2="DELETE from SALIDAREGISTRO WHERE idregistrosalida="+this.datoLote+";";
        int d2=ConexionSQL.EliminarDato(consulta2);
        System.out.println("se elmino: "+d2);
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void limpiar(){
 DefaultTableModel modelo=(DefaultTableModel) tablaEliminarRegiSalidaProd.getModel();
        modelo.getDataVector().removeAllElements();
        tablaEliminarRegiSalidaProd.updateUI();
}
    
    
public void consultaIdLote(){
        String Idlote="";
        datoLote=0;
        String consulta="select l.IDLOTE from lote as l join SALIDAREGISTRO as s on l.IDREGISTROSALIDA=s.IDREGISTROSALIDA where s.IDREGISTROSALIDA='"+con+"';"; 
        rs=ConexionSQL.Consulta(consulta);
        System.out.println("estamos en consultaidLote y la consutla es "+consulta);

        try {
            while (rs.next()){
                System.out.println(consulta);
                System.out.println(rs.getString("IDLOTE"));
                Idlote=rs.getString("IDLOTE");
                datoLote=Integer.parseInt(Idlote);
        }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       // return datoLote ;
    
    
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonRegresar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEliminarRegiSalidaProd;
    // End of variables declaration//GEN-END:variables
}
