--LISTA DE USUARIOS QUE HAN REGISTRADO LA SALIDA DE UN PRODUCTO EN EL AÑO 2020
select p.NOMBREPERSONA+' '+p.APELLIDOPERSONA AS NOMBRES,
u.LOGINUSUARIO,d.NOMBREPRODUCTO,
c.FECHAREGISTROSALIDA
from PERSONA AS p
inner join USUARIO AS u on p.IDPERSONA=u.IDPERSONA
inner join SALIDAREGISTRO AS c on c.IDUSUARIO=u.IDUSUARIO
INNER JOIN LOTE AS l ON l.IDREGISTROSALIDA= c.IDREGISTROSALIDA
INNER JOIN PRODUCTO AS d ON d.IDPRODUCTO=l.IDPRODUCTO
WHERE YEAR(c.FECHAREGISTROSALIDA) ='2020' 

--LOS 10 PROVEEDORES QUE MAS CANTIDAD DE PRODUCTOS 
--HA SOLICITADO EN EL AÑO 2020

SELECT TOP 10 p.NOMBREPROVEEDOR,d.NOMBREPRODUCTO,v.CANTIDADSOLICITUDP,
v.FECHASOLICITUDP
FROM PROVEEDORES AS p
INNER JOIN PROVEEDORSOLICITUD AS v ON p.IDPROVEEDOR=v.IDPROVEEDOR
INNER JOIN PRODUCTO AS d ON v.IDPRODUCTO=d.IDPRODUCTO
WHERE YEAR(v.FECHASOLICITUDP)='2020'
GROUP BY p.NOMBREPROVEEDOR,d.NOMBREPRODUCTO,v.CANTIDADSOLICITUDP,
v.FECHASOLICITUDP
oRDER BY v.CANTIDADSOLICITUDP DESC

--LOS 10 PROVEEDORES QUE MENOS CANTIDAD DE PRODUCTOS 
--HA SOLICITADO EN EL AÑO 2020

SELECT TOP 10 p.NOMBREPROVEEDOR,d.NOMBREPRODUCTO,v.CANTIDADSOLICITUDP,
v.FECHASOLICITUDP
FROM PROVEEDORES AS p
INNER JOIN PROVEEDORSOLICITUD AS v ON p.IDPROVEEDOR=v.IDPROVEEDOR
INNER JOIN PRODUCTO AS d ON v.IDPRODUCTO=d.IDPRODUCTO
WHERE YEAR(v.FECHASOLICITUDP)='2020'
GROUP BY p.NOMBREPROVEEDOR,d.NOMBREPRODUCTO,v.CANTIDADSOLICITUDP,
v.FECHASOLICITUDP
oRDER BY v.CANTIDADSOLICITUDP ASC


--LISTA DE USUARIOS QUE MAS REGISTROS DE ENTRADAS DE PRODUCTOS HAN TENIDO 
--CON LOS PROVEEDORES EN EL AÑO 2019
select p.NOMBREPERSONA+' '+p.APELLIDOPERSONA AS NOMBRES_COMPLETOS,u.PRIVILEGIOSUSUARIO ,
u.LOGINUSUARIO,d.NOMBREPRODUCTO,
c.FECHAENTRADAP, l.CANTIDADSOLICITUDP
from PERSONA AS p
inner join USUARIO AS u on p.IDPERSONA=u.IDPERSONA
inner join ENTRADAREGISTROPRODUCTO AS c on c.IDUSUARIO=u.IDUSUARIO
INNER JOIN PROVEEDORSOLICITUD AS l ON l.IDSOLICITUDPROVEEDOR= c.IDSOLICITUDPROVEEDOR
INNER JOIN PRODUCTO AS d ON d.IDPRODUCTO=l.IDPRODUCTO
WHERE YEAR(c.FECHAENTRADAP)='2019'

--CALCULAR LA CANTIDAD TOTAL DE PRODUCTOS EN TODA LA BODEGA

SELECT SUM (s.STOCKSECTOR) AS TOTAL_PRODUCTOS FROM SECTOR AS s
INNER JOIN LOTE AS l ON s.IDSECTOR= l.IDSECTOR
INNER JOIN PRODUCTO AS p ON p.IDPRODUCTO= l.IDPRODUCTO



--MONTO INVERTIDO EN LA BODEGA EN PRODUCTOS.

SELECT SUM (s.STOCKSECTOR* p.PRECIOUPRODUCTO) AS TOTAL_DINERO_INVERTIDO
FROM SECTOR AS s
INNER JOIN LOTE AS l ON s.IDSECTOR= l.IDSECTOR
INNER JOIN PRODUCTO AS p ON p.IDPRODUCTO= l.IDPRODUCTO


