/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author David
 */
public class Login extends javax.swing.JFrame {

     Menu m1 = new Menu();
      ResultSet rs;
     
    public Login() {
        initComponents();
        this.setTitle("SiGIn-GIZPIRIT");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jComboUsuario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBotonIniciarSesion = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Bienvenido");

        jComboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ADMINISTRADOR", "BODEGUERO", "PROVEEDOR" }));

        jLabel2.setText("Seleccione tipo de usuario");

        jLabel3.setText("Usuario");

        txtUsuario.setText("MONAL43");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Contraseña:");

        jBotonIniciarSesion.setText("Iniciar sesión");
        jBotonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonIniciarSesionActionPerformed(evt);
            }
        });

        txtPassword.setText("JOS12");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jBotonIniciarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jBotonIniciarSesion)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jBotonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonIniciarSesionActionPerformed
       //SELECCIONAR, ADMINISTRADOR, BODEGUERO, PROVEEDOR
        String usuario="",contrasenia="",permiso="";
        String [][] VecUsuarios=new String[2000][3];
        int contador=0;
        int tipoUsuario=0;
        boolean bandera=true;
        usuario=txtUsuario.getText();
        contrasenia=txtPassword.getText();
        //System.out.println("ingreso"+usuario+" "+contrasenia);
        String consulta="select top 5 LOGINUSUARIO,PASSWORDUSUARIO,PRIVILEGIOSUSUARIO from USUARIO;";
       rs=ConexionSQL.Consulta(consulta);
       if(jComboUsuario.getSelectedItem().equals("ADMINISTRADOR")){
        permiso="A";
        }else{
            if(jComboUsuario.getSelectedItem().equals("BODEGUERO")){
            permiso="B";
            }else{
            if(jComboUsuario.getSelectedItem().equals("PROVEEDOR")){
            permiso="P"; }else{
             if(jComboUsuario.getSelectedItem().equals("SELECCIONAR")){
             JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA OPCION");}
            }
            }
        }
        System.out.println(jComboUsuario.getSelectedItem()+" o "+permiso);
       
       
       
       //obtenemos longitud  
       try {
             while (rs.next()){
                 System.out.println("cantidad"+contador);
                  VecUsuarios[contador][0]=rs.getString("LOGINUSUARIO");
                  VecUsuarios[contador][1]=rs.getString("PASSWORDUSUARIO");
                  VecUsuarios[contador][2]=rs.getString("PRIVILEGIOSUSUARIO");
                    contador++; 
             }  } catch (SQLException ex) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }
            
         
        
       
        
        for(int i = 0;i<contador;i++){
            if((VecUsuarios[i][0].equals(usuario)) && (VecUsuarios[i][1].equals(contrasenia)) && (VecUsuarios[i][2].equals(permiso)) ){
            System.out.println("datos "+VecUsuarios[i][0]+" "+VecUsuarios[i][1]+""+ VecUsuarios[i][2]); 
            this.setVisible(false);
            m1.setVisible(true);
            m1.setEnabled(true);
            bandera= false;
            }    
        }
        if(bandera==false){
        JOptionPane.showMessageDialog(this, "HA INGRESADO CORRECTAMENTE");
        JOptionPane.showMessageDialog(this, "BIENVENIDO "+txtUsuario.getText());
        }else{
        JOptionPane.showMessageDialog(this, "INGRESO INCORRECTO");
        }
           
        
            /*System.out.println(rs.getString("LOGINUSUARIO")+ " "+rs.getString("PASSWORDUSUARIO"));
         
         if((usuario.equals(rs.getString("LOGINUSUARIO"))) && (contrasenia.equals(rs.getString("PASSWORDUSUARIO")))){
             JOptionPane.showMessageDialog(this, "Bienvenido "+ rs.getString("LOGINUSUARIO"));
                       
         }else{
         JOptionPane.showMessageDialog(this, "A INGRESADO MAL EL USUARIO O LA CONTRASENIA");
         }*/
        
        
        
        
              
        
        
        
        /*  boolean nohay = true;
        List<Empleado> listemp = Cemp.findEmpleadoEntities();
        for (int i = 0; i < listemp.size(); i++) {
            if (jCCField.getText().equals(listemp.get(i).getCedula()) && jContraseñaField.getText().equals(listemp.get(i).getContraseña()) && jComboUsuario.getSelectedItem().equals(listemp.get(i).getRolempleado())) {
                nohay = false;

                this.setVisible(false);
                m1.setVisible(true);
                m1.setEnabled(true);
                VentaRegistro.jTextFieldIDVendedorFactura.setText(jCCField.getText().toString());
                break;
            }
        }
        if (listemp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ningun Empleado");

        } else if (jCCField.getText().isEmpty() || jContraseñaField.getText().isEmpty() || jComboUsuario.getSelectedItem().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Llenar todos los campos");

        } else if (nohay) {
            JOptionPane.showMessageDialog(this, "el empleado no coincide con el rol o Contraseña Incorrecta");

        }*/
    }//GEN-LAST:event_jBotonIniciarSesionActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonIniciarSesion;
    private javax.swing.JComboBox<String> jComboUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
