/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import Inicio.ConexionSQL;
import Inicio.Login;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class ConsultaUsuario extends javax.swing.JInternalFrame {
     ResultSet rs;
     int seleccionar;
     
    public ConsultaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegresar2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtNombreUsuarioLogin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConUsuario = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setClosable(true);

        jButton1.setText("CONSULTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTA USUARIO");

        jButtonRegresar2.setText("REGRESAR");
        jButtonRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresar2ActionPerformed(evt);
            }
        });

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre de Usuario ");

        tablaConUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO", "DIRECCION", "TELEFONO", "LOGIN", "PASSWORD", "PRIVILEGIOS", "IDU", "IDP"
            }
        ));
        tablaConUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaConUsuario);

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButtonRegresar2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtNombreUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonRegresar2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresar2ActionPerformed
        limpiar();
        dispose();
    }//GEN-LAST:event_jButtonRegresar2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel modelo=(DefaultTableModel) tablaConUsuario.getModel();
       String consulta="select u.IDUSUARIO,p.IDPERSONA,p.NOMBREPERSONA,p.APELLIDOPERSONA," +
                "p.DIRECIONPERSONA,p.TELEFONOPERSONA,u.LOGINUSUARIO,u.PASSWORDUSUARIO,u.PRIVILEGIOSUSUARIO"+
                " from USUARIO as u join PERSONA as p on u.IDPERSONA=p.IDPERSONA;";
       
         rs=ConexionSQL.Consulta(consulta);
        
         try {
         while (rs.next()){
         System.out.println(consulta);
         System.out.println(rs.getString("NOMBREPERSONA"));
         System.out.println(rs.getString("APELLIDOPERSONA"));
         System.out.println(rs.getString("DIRECIONPERSONA"));
         System.out.println(rs.getString("TELEFONOPERSONA"));
         System.out.println(rs.getString("LOGINUSUARIO"));
         System.out.println(rs.getString("PASSWORDUSUARIO"));
         System.out.println(rs.getString("PRIVILEGIOSUSUARIO"));
         System.out.println(rs.getString("IDUSUARIO"));
         System.out.println(rs.getString("IDPERSONA"));
         
         modelo.addRow(new Object[] {rs.getString("NOMBREPERSONA"),rs.getString("APELLIDOPERSONA"),rs.getString("DIRECIONPERSONA"),
         rs.getString("TELEFONOPERSONA"),rs.getString("LOGINUSUARIO"),rs.getString("PASSWORDUSUARIO"),
         rs.getString("PRIVILEGIOSUSUARIO"),rs.getString("IDUSUARIO"),rs.getString("IDPERSONA")});

             }
         } catch (SQLException ex) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaConUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConUsuarioMouseClicked
     
    }//GEN-LAST:event_tablaConUsuarioMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  DefaultTableModel modelo=(DefaultTableModel) tablaConUsuario.getModel();
       String consulta="select u.IDUSUARIO,p.IDPERSONA,p.NOMBREPERSONA,p.APELLIDOPERSONA," +
                "p.DIRECIONPERSONA,p.TELEFONOPERSONA,u.LOGINUSUARIO,u.PASSWORDUSUARIO,u.PRIVILEGIOSUSUARIO"+
                " from USUARIO as u join PERSONA as p on u.IDPERSONA=p.IDPERSONA where u.LOGINUSUARIO='" + txtNombreUsuarioLogin.getText()+"';";

 rs=ConexionSQL.Consulta(consulta);
        
         try {
         while (rs.next()){
         System.out.println(consulta);
         System.out.println(rs.getString("NOMBREPERSONA"));
         System.out.println(rs.getString("APELLIDOPERSONA"));
         System.out.println(rs.getString("DIRECIONPERSONA"));
         System.out.println(rs.getString("TELEFONOPERSONA"));
         System.out.println(rs.getString("LOGINUSUARIO"));
         System.out.println(rs.getString("PASSWORDUSUARIO"));
         System.out.println(rs.getString("PRIVILEGIOSUSUARIO"));
         System.out.println(rs.getString("IDUSUARIO"));
         System.out.println(rs.getString("IDPERSONA"));
         
         modelo.addRow(new Object[] {rs.getString("NOMBREPERSONA"),rs.getString("APELLIDOPERSONA"),rs.getString("DIRECIONPERSONA"),
         rs.getString("TELEFONOPERSONA"),rs.getString("LOGINUSUARIO"),rs.getString("PASSWORDUSUARIO"),
         rs.getString("PRIVILEGIOSUSUARIO"),rs.getString("IDUSUARIO"),rs.getString("IDPERSONA")});

             }
         } catch (SQLException ex) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }


        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void limpiar(){
 DefaultTableModel modelo=(DefaultTableModel) tablaConUsuario.getModel();
        modelo.getDataVector().removeAllElements();
        txtNombreUsuarioLogin.setText("");
        tablaConUsuario.updateUI();
        
        
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonRegresar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConUsuario;
    private javax.swing.JTextField txtNombreUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
